import LoginPage from "./pages/Login.jsx";
import SignupPage from "./Pages/SignUp.jsx";
import Home from "./Pages/Home.jsx";
import CreateProduct from "./pages/createProduct.jsx";
import MyProducts from "./pages/myProdcucts.jsx";
import Cart from "./pages/cart.jsx";
import ProductDetails from "./pages/productDetails.jsx";
import Profile from "./pages/profile.jsx";
import CreateAddress from "./pages/createAddress.jsx";
export { SignupPage, LoginPage, Home, CreateProduct, MyProducts, Cart, ProductDetails, Profile, CreateAddress};